# Generated by Django 5.0.3 on 2024-03-31 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('builder', models.CharField(max_length=80)),
                ('address', models.CharField(blank=True, max_length=150)),
                ('phone_number', models.IntegerField(max_length=11, unique=True)),
                ('money', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Writter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.IntegerField(blank=True, max_length=11, unique=True)),
            ],
        ),
    ]
