# Generated by Django 5.0.3 on 2024-03-31 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsDetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='phone_number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='writter',
            name='phone_number',
            field=models.IntegerField(blank=True, unique=True),
        ),
    ]
