# Generated by Django 5.0.3 on 2024-03-31 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsDetails', '0003_alter_magazine_address_alter_writter_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='writter',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
