# Generated by Django 5.0.3 on 2024-03-31 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsDetails', '0004_alter_magazine_address_alter_writter_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
