# Generated by Django 5.0.3 on 2024-03-31 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsDetails', '0005_alter_magazine_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
