# Generated by Django 5.0.3 on 2024-03-31 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsDetails', '0006_magazine_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='MyNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('body', models.TextField(verbose_name='body')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsDetails.writter')),
                ('magzine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsDetails.magazine')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsDetails.topics')),
            ],
        ),
    ]
