# Generated by Django 5.0.3 on 2024-04-01 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsDetails', '0008_alter_magazine_address_alter_magazine_builder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynews',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NewsDetails.topics'),
        ),
    ]
