# Generated by Django 5.0.3 on 2024-04-01 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsDetails', '0009_alter_mynews_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='writter',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
