# Generated by Django 5.0.3 on 2024-04-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsDetails', '0010_writter_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='writter',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'male'), (2, 'fmale')], null=True, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='writter',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='users/profile_image', verbose_name='image'),
        ),
    ]
