# Generated by Django 5.0.3 on 2024-04-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsDetails', '0011_writter_gender_writter_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='writter',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='birth date'),
        ),
    ]
