# Generated by Django 5.0.3 on 2024-04-02 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsDetails', '0012_writter_birth_date'),
        ('account', '0003_remove_profile_name_profile_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mynews',
            name='author',
        ),
        migrations.RemoveField(
            model_name='mynews',
            name='magzine',
        ),
        migrations.RemoveField(
            model_name='mynews',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='magazine',
            name='money',
        ),
        migrations.AlterField(
            model_name='magazine',
            name='address',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='phone number'),
        ),
        migrations.RenameModel(
            old_name='Topics',
            new_name='Topic',
        ),
        migrations.CreateModel(
            name='MyNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('body', models.TextField(verbose_name='body')),
                ('footer', models.CharField(max_length=250, verbose_name='footer')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mynews', to='account.profile')),
                ('magzine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mynews', to='NewsDetails.magazine')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mynews', to='NewsDetails.topic')),
            ],
        ),
        migrations.DeleteModel(
            name='Writter',
        ),
        migrations.DeleteModel(
            name='MyNews',
        ),
    ]
